# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qf < Formula
  desc "Example QuickFIX/Go Applications."
  homepage "https://github.com/ackleymi/examples"
  version "2.0.17"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.17/qf_2.0.17_Darwin_x86_64.tar.gz"
      sha256 "060cbc304bb6b541f498d2197c8f2230e976988d5e9deb128b20e949397f7fa0"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.17/qf_2.0.17_Darwin_arm64.tar.gz"
      sha256 "31229efaf4bdebe8d259ab9b64a838a4941fd44b42a0673b42b0dc02aca1797b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.17/qf_2.0.17_Linux_x86_64.tar.gz"
      sha256 "242d2e16099a623ef128f9bfc3523a77053ef15ec8447440fd7cf0d75b4f597f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.17/qf_2.0.17_Linux_arm64.tar.gz"
      sha256 "bb1b9c41938d5d68fe443dcc45018cdd3deac6b23a0b2cf66c4a6d830297c6d8"
    end
  end

  def install
    bin.install "qf"
  end

  def caveats; <<~EOS
    Thanks for installing the Quickfix/Go examples
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/qtrn.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/qtrn.log</string>
  </dict>
</plist>

  EOS
  end
end
