# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qf < Formula
  desc "Example QuickFIX/Go Applications."
  homepage "https://github.com/ackleymi/examples"
  version "2.0.11"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.11/qf_2.0.11_Darwin_x86_64.tar.gz"
      sha256 "442c175d95d5560eea07b5582b6d870de06362ed05b4f2798e941cfe24699072"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.11/qf_2.0.11_Darwin_arm64.tar.gz"
      sha256 "f5a5543b7d167f3f2d89cb3536fb5faa0cbd6dc8066847ef21710b18c6dd7512"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.11/qf_2.0.11_Linux_x86_64.tar.gz"
      sha256 "46bd1a1610f4ac4b5fda4704c0522de8f92ed01f341a69e998fe3e9a532b271f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.11/qf_2.0.11_Linux_arm64.tar.gz"
      sha256 "ebbc0e07757857174104beeff68f4f948aa5cc7f00e4751b48c3adaa96419694"
    end
  end

  def install
    bin.install "qf"
  end

  def caveats; <<~EOS
    Thanks for installing the Quickfix/Go examples
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/qtrn.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/qtrn.log</string>
  </dict>
</plist>

  EOS
  end
end
