# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qf < Formula
  desc "Example QuickFIX/Go Applications."
  homepage "https://github.com/ackleymi/examples"
  version "2.0.15"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.15/qf_2.0.15_Darwin_x86_64.tar.gz"
      sha256 "c451a6162e5c0079eb0ab68ea109e6c5afeeac8bb12aef5de1bb4c8f85ab97cb"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.15/qf_2.0.15_Darwin_arm64.tar.gz"
      sha256 "1211addf686d3c5491cd0673702db16dc4b62d40261bfc0561b20cf28b494cd4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.15/qf_2.0.15_Linux_x86_64.tar.gz"
      sha256 "430f39932155faabfaa95b2c43e19fc9d8710bb9c3cfb66c37630c872b07c155"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ackleymi/examples/releases/download/v2.0.15/qf_2.0.15_Linux_arm64.tar.gz"
      sha256 "19e93b677538a7fa3183295a18fa2893bb247d01c6fce359623037f3db7494ea"
    end
  end

  def install
    bin.install "qf"
  end

  def caveats; <<~EOS
    Thanks for installing the Quickfix/Go examples
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/qtrn.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/qtrn.log</string>
  </dict>
</plist>

  EOS
  end
end
